### ISSUE TITLE
'_get_pk_value' removed in peewee 3.0.

### ISSUE THREAD

**Issue by riserperson** [peckrob/petfeedd#1]
Love this project and excited to get it working. I've assembled everything and tried installing the code in the virtual environment as instructed. No dice there, so I tried making sure all dependencies are installed globally (the raspberry pi here is single-purpose for me, so not too concerned about this) and just running the code straight. Here's what I get:

2018-06-21 13:29:00,753] ERROR in app: Exception on /api/feed [POST]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/petfeedd/src/web_worker.py", line 97, in feed_now
    feed_event = FeedEvent.create(size=1, name="On Demand")
  File "/usr/local/lib/python3.5/dist-packages/peewee.py", line 5315, in create
    inst.save(force_insert=True)
  File "/opt/petfeedd/src/models/BaseModel.py", line 14, in save
    if self._get_pk_value() is None:
AttributeError: 'FeedEvent' object has no attribute '_get_pk_value'

**Comment by peckrob** [comment]
Hello, thanks for the report.

What version of peewee do you have installed? It looks like `_get_pk_value()` was removed in 3.0.

**Comment by riserperson** [comment]
Working with current latest release, 3.5.0. I can try dropping back to an older version. Which one was petfeedd built with?

**Comment by peckrob** [comment]
Try 2.10.2. That's what my feeders are built against.

**Comment by maju6406** [comment]
@riserperson there's a typo in the petfeedd.conf.example. It should be
**servo**_feed_time=0.26
not
**sevo**_feed_time=0.26
I submitted a PR to fix that.
